// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMXn60FecnmF28YZSIOchYrezs0cnv88M',
    appId: '1:473711579608:web:d8c4cdb7e49154a7fc22ad',
    messagingSenderId: '473711579608',
    projectId: 'swipify-ac00c',
    authDomain: 'swipify-ac00c.firebaseapp.com',
    storageBucket: 'swipify-ac00c.firebasestorage.app',
    measurementId: 'G-1MNNWQZ1YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEbl3_doBhdE5SX7v4MCP2ntLcXVBKZWE',
    appId: '1:473711579608:android:f22aa7e1634769a1fc22ad',
    messagingSenderId: '473711579608',
    projectId: 'swipify-ac00c',
    storageBucket: 'swipify-ac00c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZunFAb2CZdTutwrs6959_E1cj1KMp-lE',
    appId: '1:473711579608:ios:308e5ac261e02614fc22ad',
    messagingSenderId: '473711579608',
    projectId: 'swipify-ac00c',
    storageBucket: 'swipify-ac00c.firebasestorage.app',
    iosClientId: '473711579608-lbl9m2pakfmikeq41d76q7m0jafu9kec.apps.googleusercontent.com',
    iosBundleId: 'com.example.swipify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZunFAb2CZdTutwrs6959_E1cj1KMp-lE',
    appId: '1:473711579608:ios:308e5ac261e02614fc22ad',
    messagingSenderId: '473711579608',
    projectId: 'swipify-ac00c',
    storageBucket: 'swipify-ac00c.firebasestorage.app',
    iosClientId: '473711579608-lbl9m2pakfmikeq41d76q7m0jafu9kec.apps.googleusercontent.com',
    iosBundleId: 'com.example.swipify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMXn60FecnmF28YZSIOchYrezs0cnv88M',
    appId: '1:473711579608:web:1938019f41c26c2afc22ad',
    messagingSenderId: '473711579608',
    projectId: 'swipify-ac00c',
    authDomain: 'swipify-ac00c.firebaseapp.com',
    storageBucket: 'swipify-ac00c.firebasestorage.app',
    measurementId: 'G-S0KDLL4RKB',
  );
}
